version: '3.8'

services:
  yuu:
    build: .
    container_name: yuu-chat
    restart: always
    ports:
      - "7860:7860"

    volumes:
      - ./models:/app/models

  # nginx:
  #   image: nginx:alpine
  #   container_name: yuu-nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf:/etc/nginx/conf.d
  #     - ./nginx/certbot/www:/var/www/certbot
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #   depends_on:
  #     - yuu

  certbot:
    image: certbot/certbot
    container_name: yuu-certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done'"
